language: haskell
branches:
  only:
  - master
ghc:
- 7.6
env:
  global:
  - secure: SzY6eZ8+pD9oGFXd1VIBVK/zFEtGotBFk4XsZcNT4zyuQSVqmllU4nnmWuyr98UCGnpUDq3uM8WZ34pEZbmxY7+fvpNy5r80vCSkO6uCDGlTmcdrJYQwj2jY2Z1Hs91VhSbzlSFwl5UmAYsiOUzvXk5iWACLAeCVyp3W98F17JQ=
install:
- cabal sandbox init
- cabal install -j --max-backjumps=-1
before_script:
- cd _bin
- git checkout gh-pages
- git pull origin gh-pages
- cd ..
script: yes | cp ./cabal-sandbox/bin/elm* ./_bin
after_script:
- cd _bin
- git status
- git add -all
- git config --global user.email "joey@eremondi.com"
- git config --global user.name "JoeyEremondi"
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- git push "$ELM_BINARY_URL" gh-pages >/dev/null 2>&1
- cd ..
